# All the bots constants and reusable info stored here
from discord import ActivityType

__owner__ = "Glanyx#0001 (224606487979360256)"
__botname__ = "SegaChan"
__description__ = (
    "A discord moderation bot maintained by Glanyx (https://github.com/glanyx/). "
    "SegaChan is a private Discord bot for use by Sega."
)


class Constants:
    def __init__(self):
        self.repository_link = (
            "https://github.com/glanyx/segachan/"
        )

        self.reactions = {
            "upvote": 494136380440576011,
            "downvote": 494136360194801664,
            "question": 794272398677114910,
            "spacer": 328_352_361_569_583_105,  # also referred to as 'blank'
            "sweeperbot": 361_145_141_173_682_177,
            "animated_sweeperbot": 501_214_112_504_610_816,
            "checkmark": "\N{WHITE HEAVY CHECK MARK}",
            "guantlet": 443_192_427_587_567_617,
            "yes": 507_285_695_484_919_809,
            "no": 507_287_289_282_428_962,
        }

        self.sega_heros_reactions = {
            "yes": 547_361_810_500_812_820,
            "maybe": 547_361_811_335_217_162,
            "no": 547_361_811_247_136_768,
        }

        self.discord_official_invite_codes = [
            "discord-testers",  # Discord Testers/Bug Reporting server
            "events",  # Discord Events server
            "discord-feedback",  # Discord Feedback server
            "discord-api",  # Discord API Server
            "discord-linux",  # Discord Linux server
        ]

        self.statuses = {
            "online": "<:online:400626710262972416> Online",
            "idle": "<:away:400626681066291210> Away",
            "dnd": "<:dnd:400626641916657674> Do Not Disturb",
            "offline": "<:offline:400626796112117771> Offline or Invisible",
            "streaming": "<:streaming:400626732245450762> Streaming",
            "mobile": "<:Mobile:565663254362193925>",
        }

        self.activity_enum = {
            ActivityType.playing: "Playing",
            ActivityType.listening: "Listening",
            ActivityType.watching: "Watching",
            ActivityType.streaming: "Streaming",
            ActivityType.unknown: "Unknown",
            ActivityType.custom: "Custom Status",
        }

        self.antispam = {
            "twitch": "abc",
            "discord_invites": r"discord(?:app|\.com|\.gg|\.me)\/(?:invite\/)?(?![a-zA-Z0-9\-]+\/\w)(?:[a-zA-Z0-9\-]+)",
            "twitter": r"twitter\.com(\\|\/)\S*",
            "mixer": r"mixer\.com(\\|\/)\S*",
            "youtube": r"youtube\.com(\\|\/)\S*",
            "patreon": r"patreon\.com(\\|\/)\S*",
            "paypal": r"paypal(?:\.com|\.me)(\\|\/)\S*",
            "gofundme": r"gofundme\.com(\\|\/)\S*",
            "kickstarter": r"kickstarter\.com(\\|\/)\S*",
            "kofi": r"ko-fi\.com(\\|\/)\S*",  # ko-fi.com
            "etsy": r"etsy\.com(\\|\/)\S*",
            "soundclound": r"soundcloud\.com(\\|\/)\S*",
        }

        self.log_channels = [
            "bot-logs",
            "deleted-logs",
            "member-logs",
            "name-change-logs",
            "voice-logs",
            "reaction-logs",
        ]

        # All groups require a _default color.
        self.log_colors = {
            "user_action": {
                "_default": 0xFF8C00,
                "Mute": 0xFFCC00,
                "Unmute": 0xFFCC00,
                "Warn": 0xFFEF00,
                "Ban": 0xE50000,
                "Kick": 0x0083FF,
                "reactionAdd": 0x64997D,
                "reactionRemove": 0xED8F45,
                "worldFilter": 0x00B2EE,
            }
        }

        self.destiny_voice_channel_names = [
            "Abyss",
            "Acolyte",
            "Adjuticator",
            "Adonna",
            "Agah",
            "Agema",
            "Agenda-5",
            "Ahamkara",
            "Aksis",
            "Aksor",
            "Alak-Hul",
            "Alessa",
            "Alpha Lupi",
            "Alzok",
            "Amanda",
            "Amytis",
            "Ana Bray",
            "Andal",
            "Anomaly",
            "Arach",
            "Aral",
            "Arath",
            "Archon",
            "Arcblade",
            "Arcology",
            "Arcstrider",
            "Armillary",
            "Aru'Un",
            "Ascendant Raisins",
            "Asher",
            "Atheon",
            "Aurash",
            "Avalon",
            "Azzir",
            "Baby Dog",
            "B'Ael",
            "Ballyhoo",
            "Bamberga",
            "Banshee-44",
            "Barricade",
            "Baseline",
            "Baxx",
            "Beltrik",
            "Bladedancer",
            "Blight",
            "Bone",
            "Bracus",
            "Brakion",
            "Brask",
            "Bray",
            "Breakpoint",
            "Brevin",
            "Brother Vance",
            "Bryl",
            "Cabal",
            "Caliban",
            "Calus",
            "Camo",
            "Captain America",
            "Carybdis",
            "Celery",
            "Celestial",
            "Charlemagne",
            "Chioma",
            "Chronoglass",
            "Cipher",
            "Citan",
            "Clovis",
            "Coldheart",
            "Colovance",
            "Complex",
            "Compute",
            "Confused",
            "Copperhead",
            "Corrector",
            "Cozmo-23",
            "Crescent",
            "Crest",
            "Crota",
            "Crux",
            "Cryptarch",
            "Dakaua",
            "Darci",
            "Darkblade",
            "Dawnblade",
            "Deathsinger",
            "DeeJ",
            "Defiant",
            "Devastation",
            "Devils",
            "Devrim",
            "Dictata",
            "Dinklebot",
            "Dogma",
            "Draksis",
            "Drang",
            "Dredgen",
            "Dreg",
            "Drevis",
            "Droysen",
            "Dunemarchers",
            "Echo",
            "EDZ",
            "Ego",
            "Eliksni",
            "Emperor",
            "Emissary",
            "Encore",
            "Eriana-3",
            "Eris Morn",
            "Eternity",
            "Eva Levante",
            "Everis",
            "Exile",
            "Exo Stranger",
            "Exotic",
            "Fallen",
            "Fatebringer",
            "Feizel",
            "Felwinter",
            "Fenchurch",
            "Finnala",
            "Flashpoint",
            "Foetracer",
            "Foresight",
            "Gatekeeper",
            "Gensym",
            "Ghaul",
            "Ghost",
            "Gilmanovich",
            "Gjallarhorn",
            "GodWave",
            "Golden",
            "Golgoroth",
            "Gornuk",
            "Gravekeeper",
            "Grayor",
            "Grenade",
            "Guide",
            "Gulrot",
            "Halak",
            "Halfdan",
            "Hallowfire",
            "Hammer",
            "Harbinger",
            "Harpy",
            "Hassa",
            "Haunted",
            "Havoc",
            "Hawkmoon",
            "Hawthorne",
            "Hemisphere",
            "Hezen",
            "Hildean",
            "Hohmann",
            "Holborn",
            "Holliday",
            "Honeycomb",
            "HopeEater",
            "Hunter",
            "Hygiea",
            "Illyn",
            "Io",
            "Irxis",
            "Ir Yut",
            "Ivonovich",
            "Jacobson",
            "Jagi",
            "Jalaal",
            "Jaren",
            "Jolyon",
            "Jovians",
            "Judgment",
            "Kadi 55-30",
            "Kagathos",
            "Kagoor",
            "Kaharn",
            "Kaliks",
            "Kay",
            "Keksis",
            "Kells",
            "Kellship",
            "Khvostov",
            "Kingfisher",
            "Kings",
            "Knight",
            "Knucklehead",
            "Korus",
            "Kovik",
            "Kraghoor",
            "Kranox",
            "Kressler",
            "Krughor",
            "Lakpha",
            "Lakshmi-2",
            "Lancelot",
            "Lanshu",
            "Legendary",
            "Lincoln",
            "Lissyl",
            "Little Light",
            "Long Walk",
            "Lokaar",
            "Loken",
            "Lomar",
            "Lonwabo",
            "Lord Saladin",
            "Lord Shaxx",
            "Louis",
            "LV36 Captain",
            "Malahayati",
            "Malok",
            "Malphur",
            "Mamba",
            "Man o'War",
            "Mara Sov",
            "Maraid",
            "Martyr",
            "Massyrian",
            "Matador 64",
            "Mecher",
            "Medulla",
            "Mengoor",
            "Merciless",
            "Micha",
            "MIDA",
            "Milestone",
            "Mindbreaker",
            "Minerva",
            "Minotaurs",
            "Minuet",
            "Mir",
            "Modris",
            "Moon",
            "Moonrider",
            "Mormu",
            "M'Orn",
            "Murmur",
            "Nanotech",
            "Nascia",
            "Nemo",
            "Nessus",
            "Nezarec",
            "Nicha",
            "Nighthawk",
            "Nightshade",
            "Ning",
            "Noble",
            "Nolg",
            "Novarro",
            "Oboe",
            "Offense",
            "Ogre",
            "Omnigul",
            "Oort",
            "Optimacy",
            "Orbiks",
            "Oracle",
            "Origin",
            "Oryx",
            "Osiris",
            "Oversoul",
            "Pacific",
            "Palamon",
            "PallasBane",
            "Parixas",
            "Paskin",
            "Peacekeepers",
            "Peekis",
            "Perseverance",
            "Persuader",
            "Petra",
            "Philomath",
            "Phoenix",
            "Piccolo",
            "Pinar",
            "Pirsis",
            "Praxic",
            "Prophet",
            "Prosecutor",
            "Prospector",
            "Protheon",
            "Psion",
            "Qiao",
            "Qodron",
            "Queenbreakers",
            "Qugu",
            "Quickfang",
            "Quria",
            "Racin",
            "Radegast",
            "Rafriit",
            "Rahndel",
            "Raiden",
            "Ralph the Chicken",
            "Rapture",
            "Rasputin",
            "Rat King",
            "Red Legion",
            "Redjack",
            "Reefborn",
            "Relentless",
            "Revenge",
            "Rezyl",
            "Rience",
            "Rift",
            "Riksis",
            "Riskrunner",
            "Roni",
            "Rose",
            "SABER",
            "Saint-14",
            "Sardok",
            "Sardon",
            "Sathona",
            "Savathun",
            "Saviks",
            "Sayeth",
            "Scathelocke",
            "Scavenger",
            "Scorpion",
            "Scout",
            "Sedia",
            "Segoth",
            "Sekrion",
            "Sepiks",
            "Seven-Six-Five",
            "Shadestep",
            "Shadowshot",
            "Shelter",
            "Shieldbreaker",
            "Shim",
            "Shirazi",
            "Shiro-4",
            "Shotgun",
            "Showrunner",
            "Shift",
            "Shuro",
            "Sidearm",
            "Siege Engine",
            "Silent Fang",
            "Silimar",
            "Simiks",
            "Simulator",
            "Skate",
            "Skolas",
            "Skoriks",
            "Skorri",
            "Skriviks",
            "Skullfort",
            "Skyburners",
            "Sloane",
            "Sojourner",
            "Solarium",
            "Solkis",
            "Sovereign",
            "Speedpunk",
            "Spindle",
            "Squid",
            "Starchaser",
            "Starcutters",
            "Stormcaller",
            "Stormtrance",
            "Sturm",
            "Sundaresh",
            "Sunshot",
            "Suros",
            "Sweeper Bot",
            "Swiftling",
            "Swordbearer",
            "Sylok",
            "Synthoceps",
            "Ta'Aurc",
            "Taeko",
            "Taishibethi",
            "Taken",
            "Tango",
            "Talon",
            "Taniks",
            "Taox",
            "Tarlowe",
            "Teben",
            "Techeun",
            "Telesto",
            "Telstar",
            "Telthor",
            "Tempests",
            "Templar",
            "Tescan",
            "Tevis",
            "Thalnok",
            "Thaviks",
            "The Speaker",
            "The Traveler",
            "Theosyion",
            "Tho'Ourg",
            "Thrall",
            "Thuria",
            "Timepiece",
            "Timewarp",
            "Timur",
            "Tinette",
            "Titan",
            "Token",
            "Toland",
            "Tover",
            "Transversive",
            "Trax",
            "Trenn",
            "Tubach",
            "Tuyet",
            "Uldren Sov",
            "Unassailable",
            "Uriel",
            "Urrox",
            "Urzok",
            "Uzoma",
            "Va'Ase",
            "Valiant",
            "Valus",
            "Vandal",
            "Vekis",
            "Veliniks",
            "Velor",
            "Vengeance",
            "Venj",
            "Verdict",
            "Vestan",
            "Vestian",
            "Vex",
            "Vigilance",
            "Virixas",
            "Voidwalker",
            "Vorlog",
            "Vosik",
            "Ward",
            "Warlock",
            "Warmind",
            "Warpriest",
            "Warsat",
            "Wayfarer",
            "Wei Ning",
            "Weksis",
            "Wicked",
            "Wildwood",
            "Wintership",
            "Wizened",
            "Wolves",
            "WorldRender",
            "Wormfood",
            "Wormwood",
            "Wrecked",
            "Xander 99-40",
            "Xivu",
            "Xol",
            "Xur",
            "Xyor",
            "Yavek",
            "Yor",
            "Zahn",
            "Zarin",
            "Zhalo",
            "Zire",
            "Zydron",
            "Zyre",
            "Zyrok",
            "Op Piccolo",
            "Argos",
            "Val Ca'uor",
            "Benedict-9940",
            "Gauntlet",
            "Greed",
            "Loyalty",
            "War",
            "Sol",  # Chalice is "Greed", Dog is "Loyalty", Axes is "War", and Sun is "Sol"
            "dmg04",
            "Earth",
            "Venus",
            "Mars",
            "Mercury",
            "Dreadnaught",
            "Dreaming City",
            "Tangled Shore",
            "Gambit",
            "Fikrul",
            "Elykris",
            "Hiraks",
            "Araskes",
            "Reksis Vahn",
            "Kaniks",
            "Pirrha",
            "Yaviks",
            "Queen's Wrath",
            "Greenraven",
            "Cermonial Bathers",
            "Master Ives",
        ]

        # Message Templates
        self.infraction_header = "You've received a **{action_type}** on **{guild}**. A message from the moderators:\n\n"
        self.footer_with_modmail = "\n\nIf you have questions you may respond to this message and it'll be relayed to **{guild}**'s moderators."
        self.footer_no_modmail = "\n\nIf you have questions about this please reach out to **{guild}**'s moderators."
        self.footer_appeals_server = "\n\nIf you are unable to reach the mod team, such as to appeal a ban you may join this shared Appeals Server: {appeals_invite}"

        self.normalize_regex = "[^a-z0-9]"
        self.modmail_read_receipts = "Thanks for sending us this message. This is to indicate that we've received it. Going forward you will receive a reaction on your message showing when the message is delivered as: ✉"

        # Static Messages
        self.antispam_quickmsg = "Please do not spam our server. This includes sending too many messages too quickly. Please make sure you don't split your thoughts across multiple messages and keep it to one or two messages, and don't copy and paste or send the same message in multiple channels."
        # Production Channels
        self.prod_bot_media_spam = 503_382_909_387_014_154
